### ISSUE TITLE
Add new step not working in show Preview

### ISSUE THREAD

**Issue by Sergio-Daniel-Pires** [windmill-labs/windmill-vscode#14]
How to reproduce:

1. Install extension in vscode (I'm using v0.2.35)
2. Open .flow windmill file
3. Ctrl + Shift + P and "Show Preview"
4. Try to add a new step into flow clicking on "+" button

Error message:
```
Refused to frame '' because it violates the following Content Security Policy directive: "frame-src 'self' hub.windmill.dev".
```

**Comment by chevdor** [comment]
I am running into the same issue. I saw videos using an older version of the extension and tried 0.2.4 (1y old) without more success.

My context: self hosted, k8s, traefik.
The dev console showed issues with cookies. I could fix those using a traefik middleware:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: windmill
  name: cookie-secure-samesite
spec:
  headers:
    customRequestHeaders:
      Set-Cookie: "SameSite=None; Secure"
    customResponseHeaders:
      # Content-Type: "text/html; charset=UTF-8"
      Set-Cookie: "SameSite=None; Secure"
```

Now clicking this [+] shows only an info in the dev console:
```
document | Quirks Mode | data:text/html,<script>onresize=function(){parent.postMessage(0,'*')}</script>
```

Running in Brave works all fine. I am on `0.2.35`.
