### ISSUE TITLE
Interacting with VSCode Windmill extension on flows changes the formatting in Yaml file

### ISSUE THREAD

**Issue by erfansaheb** [windmill-labs/windmill-vscode#21]
When I click on objects on the UI it changes the formatting of the `flow.yaml` file. 
Examples:
```
input_transforms:
          obj1:
            type: javascript
            expr: 'results.d[0]'
```  
changes to:
```
input_transforms:
          obj1:
            type: javascript
            expr: results.d[0]
```
This increases the diffs for Github and is a bit inconvenient.
This doesn't happen to all the fields and I could not find a pattern

![Image](https://github.com/user-attachments/assets/9d184499-7306-46cc-96cd-f36eefdf8906)
